package com.security.job.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "job_post")
public class JobEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String jobTitle;
    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String applicationLink;
    @DynamoDBRangeKey(attributeName = "dateOfRelease")
    private Long dateOfRelease;

    @DynamoDBAttribute
    private Long applicationOpenTill;

    @DynamoDBAttribute
    private String experience;
    @DynamoDBAttribute
    private String Location;
}
