package com.security.job.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "test")
public class JobEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String jobTitle;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String applicationLink;

    @DynamoDBAttribute
    private String dateOfRelease;

    @DynamoDBAttribute
    private String applicationOpenTill;

    @DynamoDBAttribute
    private String experience;

}
